### ISSUE TITLE
SCF ERROR array must not contain infs or NaNs

### ISSUE THREAD

**Issue by lucienwb** [pyscf/pyscf#1494]
Hi, I am runing an atom calculation using pyscf, see below, but got an error ```ValueError: array must not contain infs or NaNs```. I put the full error traceback after the script. The error seems to be raised by asarray_chkfinite function. Does anybody know how to solve this problem. Thank you!
pyscf version 2.1.1 and system is MacOS (M1)

```
from pyscf import gto,dft

mol = gto.M(
    atom = '''
        C    0.00000000    0.00000000    0.00000000
            ''',
    spin=2,
    charge=0,
)
mol.basis='ccpvtz'
mol.cart=False
mol.build()

myrks=dft.RKS(mol)
myrks.xc='SCAN'
myrks.grids.atom_grid=(99,590)
myrks.kernel()
```
```
python -u "/Users/Desktop/Python/atom.py"
Traceback (most recent call last):
  File "/Users/Desktop/Python/atom.py", line 17, in <module>
    myrks.kernel()
  File "<string>", line 2, in kernel
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/pyscf/scf/hf.py", line 1692, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/pyscf/scf/hf.py", line 173, in kernel
    mo_energy, mo_coeff = mf.eig(fock, s1e)
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/pyscf/scf/rohf.py", line 380, in eig
    e, c = self._eigh(fock, s)
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/pyscf/scf/hf.py", line 1526, in _eigh
    return eig(h, s)
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/pyscf/scf/hf.py", line 1165, in eig
    e, c = scipy.linalg.eigh(h, s)
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/scipy/linalg/decomp.py", line 445, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/scipy/_lib/_util.py", line 293, in _asarray_validated
    a = toarray(a)
  File "/opt/miniforge/base/envs/py39/lib/python3.9/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
```

**Comment by susilehtola** [comment]
Which version of PySCF and libxc do you have? How did you install them? SCAN had many numerical issues in the past but they were fixed a few years ago in libxc 5.1.0. Running your input with PySCF 2.1.1 and Libxc 5.2.2 I get the following output
```
$ python scan.py 
converged SCF energy = -37.8339863490095
```

Note also that SCAN is a numerically a truly horrible functional. You should use r2SCAN instead, it is better behaved, even if it still suffers from similar issues, see https://doi.org/10.1063/5.0121187

**Comment by lucienwb** [comment]
@susilehtola Thank you for your answer. I am using pyscf version 2.1.1, installed by ``pip install pyscf`` command. I am not sure which version of libxc and xcfunc will be installed in such way, and I still have the same "NaN/inf" error. Should I compile the code or build it offline to make sure pyscf works with latest libxc?

**Comment by susilehtola** [comment]
According to #1490 the pip package isn't using libxc; the NaNs may arise from xcfun. It might be best to compile the code yourself.

**Comment by lucienwb** [comment]
@susilehtola Thanks! I recomplied pyscf on my mac now I get the correct result. Thank you!
