### ISSUE TITLE
pyscf read molpro orbitals

### ISSUE THREAD

**Issue by lqhenwunai** [pyscf/pyscf#448]
Dear all,

I want to use pyscf to read molecular orbitals from molpro. My molpro version is  Version 2015.1. My pyscf input for a La atom is:

import os
import numpy as np
from pyscf import gto, scf,symm,cc,tools
from pyscf.cc import ccsd_t
from pyscf.gto.basis import parse_molpro
from pyscf.x2c import x2c

mol=gto.Mole()
#unit in angstrom
mol.atom='''La 0 0 0
'''
mol.symmetry='d2h'

dirnow = os.path.realpath(os.path.join(file, '..'))
basis_file_from_user = os.path.join(dirnow, 'cc-pvtz-x2c.dat')
mol.basis={'La':basis_file_from_user}

#-------------------------------------
#The following part is copied from examples/gto/30-read_molpro_orb.py

dat = open('orb.matrop').read().split('\n')
dat = ''.join(dat[2:-2]) # [2:-2] to skip comments
dat = np.array([float(x) for x in dat.split(',')[:-1]]) # [:-1] to remove last comma

#all orbitals in molpro symmetry order
#The dims is modified accordingly
dims = [22,16,16,11,16,11,11,6] # orbitals in each irrep

off = 0
molpro_mo = []
for i, nd in enumerate(dims):
molpro_mo.append(dat[off:off+nd2].reshape(nd,nd))
off += nd2
mo = []
for i, ir in enumerate(mol.irrep_id):
molpro_id = symm.param.IRREP_ID_MOLPRO['D2h'][ir]-1
mo.append(np.dot(mol.symm_orb, molpro_mo[molpro_id]))
mo = np.hstack(mo)

#print np.einsum('ji,jk,ki->i', mo, mol.intor('cint1e_ovlp_sph'), mo)
#end of copy
#------------------------------------------------------------------------------------

mol.max_memory=8000
mol.charge=0
mol.spin=1 #molpro convention
mol.output='Lavtz.out'
mol.build()
hf=scf.RHF(mol).x2c()
hf.kernel()

However, when I run the script, it returns with:
for i, ir in enumerate(mol.irrep_id):
TypeError: 'NoneType' object is not iterable

I tried to reproduce the result of the original example input, it returns with a different error message, but at least it enters in the regarding loop.
mo.append(np.dot(mol.symm_orb, molpro_mo[molpro_id]))
ValueError: shapes (10,3) and (7,7) not aligned: 3 (dim 1) != 7 (dim 0)

I don't know what is wrong with my La input.

Many thanks for your help.

**Comment by fishjojo** [comment]
Hi @lqhenwunai,
You need to call `mol.build()` before iterating through `mol.irrep_id`.
Xing

**Comment by lqhenwunai** [comment]
Hi Xing,

Thanks, now the "TypeError: 'NoneType' object is not iterable" is solved.

But I got a similar error as the example case
"    mo.append(np.dot(mol.symm_orb[i], molpro_mo[molpro_id]))
ValueError: shapes (145,33) and (22,22) not aligned: 33 (dim 1) != 22 (dim 0)"

I suspect the molpro format is changed but I am not sure. Do you remember which version of molpro were you referring to?

**Comment by sunqm** [comment]
The shape for each symmetry adapted orbital doesn't match the corresponding molpro's shape. What's the shape of pyscf symmetry adapted orbitals?
```
print([c.shape for c in mol.symm_orb])
```

Are the shape in your script taken from molpro output? The sum of dims does not equal to 145, which is the total number of AOs found by pyscf.
```
#The dims is modified accordingly
dims = [22,16,16,11,16,11,11,6] # orbitals in each irrep
```

**Comment by lqhenwunai** [comment]
Dear all,

I am now using pyscf to calculate the Gd2 molecule reading molecular orbitals from Molpro. The Molpro SCF has smoothly been converged, but the pyscf is still struggling to converge. I am not sure if the Molpro orbitals have been successfully loaded. Can you please give me any suggestions?

Many thanks. 

My input is as follows:
--------------------------------------------------------------------
mol=gto.Mole()
#unit in angstrom
mol.atom='''Gd 0 0 1.428786
          Gd 0 0 -1.428786'''

input_name  = __file__
filename    = input_name[:-3]
output_name = filename+'.out'
mol.output=output_name

dirnow = os.path.realpath(os.path.join(__file__, '/home/projects/Ln2/Basis/NWCHEM-format'))
basis_file_from_user = os.path.join(dirnow, 'cc-pvdz-x2c.dat')
mol.basis={'Gd':basis_file_from_user}


dat = open('orb.matrop').read().split('\n')
dat = ''.join(dat[2:-2]) # [2:-2] to skip comments
dat = np.array([float(x) for x in dat.split(',')[:-1]]) # [:-1] to remove last comma

# Number of core orbitals:          46 (  11   5   5   2  11   5   5   2 )
# Number of closed-shell orbitals:   9 (   3   1   1   0   2   1   1   0 )
# Number of active  orbitals:       18 (   3   3   3   1   3   2   2   1 )
# Number of external orbitals:      95 (  17  11  11   7  18  12  12   7 )


mol.max_memory=6000
mol.charge=0
mol.spin=18  #molpro convention
mol.verbose=6
mol.symmetry='D2h'
mol.build()
hf=scf.RHF(mol).x2c()
hf.irrep_nelec={'Ag':(17,14),'B3u':(9,6),'B2u':(9,6),'B1g':(3,2),'B1u':(16,13),'B2g':(8,6),'B3g':(8,6),'Au':(3,2)}


dims=[34,20,20,10,34,20,20,10]

off = 0
molpro_mo = []
for i, nd in enumerate(dims):
    molpro_mo.append(dat[off:off+nd**2].reshape(nd,nd))
    off += nd**2
mo = []
for i, ir in enumerate(mol.irrep_id):
    molpro_id = symm.param.IRREP_ID_MOLPRO['D2h'][ir]-1
    mo.append(np.dot(mol.symm_orb[i], molpro_mo[molpro_id]))
mo = np.hstack(mo)


hf.kernel()
-------------------------------------------------------------

**Comment by sunqm** [comment]
Is the error still 
ValueError: shapes (145,33) and (22,22) not aligned: 33 (dim 1) != 22 (dim 0)"

The dimensions seems incorrect. The statement dims=[34,20,20,10,34,20,20,10] indicates that there are in total 168 orbitals. The number of AOs from the error msg shows there are 145 AOs.

For the convergence problem, you may try the second-order algorithm to converge SCF
```
mf.newton().run()
```

**Comment by sunqm** [comment]
It is likely an issue of parsing Molpro orb.matrop file. pyscf does not have a parser to read molpro orbital files. More discussions can be https://mattermodeling.stackexchange.com/questions/9474/interface-between-pyscf-and-molpro
